language: python

python:
    - 3.5

env:
  - CONDA_DEPS="pip numpy scipy matplotlib pandas jupyter nbformat nbconvert" PIP_DEPS="notedown"

before_install:
- yes "" | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get update -y
- sudo apt-get install -y
     inkscape
     texlive-fonts-recommended
     texlive-latex-extra
     texlive-latex-recommended
     texlive-xetex
- wget https://github.com/jgm/pandoc/releases/download/1.17.0.2/pandoc-1.17.0.2-1-amd64.deb > /var/cache/apt/archives/pandoc-1.17.0.2-1-amd64.deb
- sudo apt-get install -y pandoc
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
# Install conda only if necessary
- command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda install python=$TRAVIS_PYTHON_VERSION $CONDA_DEPS
- travis_retry pip install $PIP_DEPS

script: /bin/bash gh-publisher-scripts/gh-publisher.sh

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
- conda clean --tarballs --packages --index-cache
- rm -rf $HOME/miniconda/pkgs/cache
- xargs rm <installed_files.txt

cache:
  directories:
    - $HOME/miniconda
